language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install flask_wtf
  - pip install flask_wtforms 
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
